# Generated by Django 4.0.3 on 2022-03-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_projectdocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocuments',
            name='uploaded_file_name',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
